# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: <a>http://www.numpy.org/</a>

In [1]:
from numpy import *

In [2]:
# declare a vector using a list as the argument
v = array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
# declare a matrix using a nested list as the argument
M = array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [4]:
# still the same core type with different shapes
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [5]:
M.size

4

In [6]:
# arguments: start, stop, step
x = arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [8]:
logspace(0, 10, 10, base=e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [9]:
x, y = mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [10]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [11]:
from numpy import random

In [12]:
random.rand(5,5)

array([[0.83492239, 0.37505049, 0.44113315, 0.20191896, 0.13143573],
       [0.17064413, 0.64904083, 0.82817669, 0.73247713, 0.97997328],
       [0.94085023, 0.66827787, 0.6754081 , 0.4522449 , 0.09963147],
       [0.34668653, 0.05185067, 0.79066422, 0.95013378, 0.03132977],
       [0.8215444 , 0.16123067, 0.24594251, 0.5460305 , 0.038036  ]])

In [13]:
# normal distribution
random.randn(5,5)

array([[-1.01674968, -0.80391629, -1.49180342,  0.29633381, -1.08566128],
       [-0.55259655, -1.2772158 ,  1.14769887,  1.43503622,  0.84936637],
       [-0.12361191, -1.30590607,  0.90808764, -0.87830477,  0.69067888],
       [-1.09999148, -0.52411538, -1.29882826,  0.74867556, -0.8242142 ],
       [-1.48557907,  0.10944114, -0.17351751, -0.65266063,  2.0973076 ]])

In [14]:
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
M.itemsize

8

In [16]:
M.nbytes

32

In [17]:
M.ndim

2

In [18]:
v[0], M[1,1]

(1, 4)

In [19]:
M[1]

array([3, 4])

In [20]:
# assign new value
M[0,0] = 7
M

array([[7, 2],
       [3, 4]])

In [21]:
M[0,:] = 0
M

array([[0, 0],
       [3, 4]])

In [22]:
# slicing works just like with lists
A = array([1,2,3,4,5])
A[1:3]

array([2, 3])

In [23]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [24]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [25]:
# index masking
B = array([n for n in range(5)])
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 2])

### Linear Algebra

In [26]:
v1 = arange(0, 5)

In [27]:
v1 + 2

array([2, 3, 4, 5, 6])

In [28]:
v1 * 2

array([0, 2, 4, 6, 8])

In [29]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [30]:
dot(v1, v1)

30

In [31]:
dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [32]:
# cast changes behavior of + - * etc. to use matrix algebra
M = matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [33]:
# inner product
v.T * v

array([ 1,  4,  9, 16])

In [34]:
C = matrix([[1j, 2j], [3j, 4j]])
C

matrix([[0.+1.j, 0.+2.j],
        [0.+3.j, 0.+4.j]])

In [35]:
conjugate(C)

matrix([[0.-1.j, 0.-2.j],
        [0.-3.j, 0.-4.j]])

In [36]:
# inverse
C.I

matrix([[0.+2.j , 0.-1.j ],
        [0.-1.5j, 0.+0.5j]])

### Statistics

In [37]:
mean(A[:,3])

23.0

In [38]:
std(A[:,3]), var(A[:,3])

(14.142135623730951, 200.0)

In [39]:
A[:,3].min(), A[:,3].max()

(3, 43)

In [40]:
d = arange(1, 10)
sum(d), prod(d)

(45, 362880)

In [41]:
cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [42]:
cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [43]:
# sum of diagonal
trace(A)

110

In [44]:
m = random.rand(3, 3)
m

array([[0.70284881, 0.04287345, 0.47865066],
       [0.95848396, 0.75261975, 0.14481617],
       [0.07497906, 0.64746987, 0.4884195 ]])

In [45]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=0)

(0.9584839643618734, array([0.95848396, 0.75261975, 0.4884195 ]))

In [46]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [47]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [48]:
# modify the array
B[0,0:5] = 5
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [49]:
# also changed
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [50]:
# creates a copy
B = A.flatten()
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [51]:
# can insert a dimension in an array
v = array([1,2,3])
v[:, newaxis], v[:,newaxis].shape, v[newaxis,:].shape

(array([[1],
        [2],
        [3]]), (3, 1), (1, 3))

In [52]:
repeat(v, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [53]:
tile(v, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [54]:
w = array([5, 6])

In [55]:
concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [56]:
# deep copy
B = copy(A)

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [57]:
import numpy as np
arr = np.arange(0,10)

In [58]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [60]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/Users/pymacbit/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
# Also warning, but not an error instead infinity
1/arr

/Users/pymacbit/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [63]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [64]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [66]:
np.max(arr) #same as arr.max()

9

In [67]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [68]:
np.log(arr)

/Users/pymacbit/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [69]:
#Creating sample array
arr = np.arange(0,11)

In [70]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [71]:
#Get a value at an index
arr[8]

8

In [72]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [73]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [74]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [75]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [77]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [78]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [79]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [80]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [82]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [83]:
# Getting individual element value
arr_2d[1,0]

20

In [84]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [85]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [86]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [87]:
#Set up matrix
arr2d = np.zeros((10,10))

In [88]:
#Length of array
arr_length = arr2d.shape[1]

In [89]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [90]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [91]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [92]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [94]:
bool_arr = arr>4

In [95]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [96]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [97]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [99]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [100]:
np.array(my_list)

array([1, 2, 3])

In [101]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [102]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [103]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [105]:
np.zeros(3)

array([0., 0., 0.])

In [106]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [107]:
np.ones(3)

array([1., 1., 1.])

In [108]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [109]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [110]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [111]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [112]:
np.random.rand(2)

array([0.95921819, 0.58342884])

In [113]:
np.random.rand(5,5)

array([[0.55978359, 0.94468217, 0.86581304, 0.60389871, 0.07953615],
       [0.41709866, 0.9526085 , 0.64753779, 0.57978784, 0.06922816],
       [0.23851097, 0.62577425, 0.17002206, 0.71665746, 0.50489177],
       [0.75194892, 0.26092331, 0.28237539, 0.96108109, 0.77588767],
       [0.66412617, 0.28406033, 0.64904413, 0.11283398, 0.29056511]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [114]:
np.random.randn(2)

array([1.20862425, 0.24658315])

In [115]:
np.random.randn(5,5)

array([[ 0.27206711,  1.57478062,  1.71839661,  1.73770941, -0.74397137],
       [-1.03363161, -0.66492389,  0.34306375,  1.86223264, -1.23811379],
       [-0.11325262,  0.02656224, -1.36006267, -0.15541127, -1.24438998],
       [ 0.43981362, -0.18386554, -1.29880117, -1.40537518, -1.73208563],
       [-0.72469502, -0.99993559, -0.46902931, -0.43621617, -1.94564108]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [116]:
np.random.randint(1,100)

50

In [117]:
np.random.randint(1,100,10)

array([60, 15, 29, 94, 15, 87, 29,  1, 21, 68])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [118]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [120]:
ranarr

array([ 1,  6, 24, 15, 10,  9, 34, 23, 46, 17])

## Reshape
Returns an array containing the same data with a new shape.

In [121]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [122]:
ranarr

array([ 1,  6, 24, 15, 10,  9, 34, 23, 46, 17])

In [123]:
ranarr.max()

46

In [124]:
ranarr.argmax()

8

In [125]:
ranarr.min()

1

In [126]:
ranarr.argmin()

0

## Shape

Shape is an attribute that arrays have (not a method):

In [127]:
# Vector
arr.shape

(25,)

In [128]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [129]:
arr.reshape(1,25).shape

(1, 25)

In [130]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [131]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [132]:
arr.dtype

dtype('int64')

### Linear Algebra

In [133]:
v1 = arange(0, 5)

In [134]:
v1 + 2

array([2, 3, 4, 5, 6])

In [135]:
v1 * 2

array([0, 2, 4, 6, 8])

In [136]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [137]:
dot(v1, v1) 
# product of two array

30

In [145]:
np.exp(arr)
#Calcualting exponential (e^)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [146]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [147]:
np.log(arr)

/Users/pymacbit/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# NumPy Exercises

#### Import NumPy as np

In [149]:
import numpy as np

#### Create an array of 10 zeros 

In [150]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [151]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [152]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [153]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [154]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [155]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [156]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [157]:
np.random.rand(1)

array([0.10917065])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [158]:
np.random.randn(25)

array([-1.21624459,  0.68782154, -1.27272844, -1.05744095, -0.38993829,
       -0.77654281,  0.22231807,  1.03752651, -0.52288213,  0.1033376 ,
        0.66338058, -0.72499864,  0.93087532, -0.45758446,  1.73527009,
        1.46555141,  0.04686976,  0.91065079, -1.62960601, -0.52141823,
        0.12127969,  0.58068804, -1.53193764,  0.28278191, -0.39404172])

#### Create the following matrix:

In [159]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [160]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [161]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [162]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [163]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [164]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [165]:
mat[3,4]

20

In [166]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [167]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [168]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [169]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [170]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [171]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [172]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [173]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [174]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!